/**
 * @file   static_config.hpp
 * @author Stefan Kiel 
 * @date   Mon Aug  9 16:00:43 2010
 * 
 * @brief  Static configuration
 * 
 * 
 */


#ifndef __STATIC_CONFIG_HPP__
#define __STATIC_CONFIG_HPP__

// Intervallbibliothek auswählen
#define USE_IV_CXSC 1
//#define USE_IV_BOOST 1

namespace config 
{
  namespace functions 
  {
    /// determines the default maximum derivative order generated by the FDeriv template
    const int DEFAULT_DERIV_ORDER = 3;
  }
}

#endif /*__STATIC_CONFIG_HPP__*/

